name: Deploy to EC2

on:
   push:
     branches:
        -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v5

    - name: Runs some bash commands
      run: ls -al
