name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy code to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "./"
        target: "/home/ubuntu/"

    - name: Deploy to web directory and restart nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Current directory and files:"
          ls -al
          echo "Current user:"
          whoami
          echo "Copying files to web directory..."
          sudo cp -r /home/ubuntu/* /var/www/html/
          echo "Setting proper permissions..."
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          echo "Testing nginx configuration..."
          sudo nginx -t
          echo "Restarting nginx..."
          sudo systemctl restart nginx
          echo "Deployment completed successfully!"
